### PR TITLE
Sync APIs from karmada repo based on v1.6.0

### PR DESCRIPTION
**Pull request by RainbowMango**
This PR syncs APIs from karmada-io/karmada for v1.6.0.

Fixes https://github.com/karmada-io/karmada/issues/3755

### CODE REVIEW

**Comment by calvin0327** [comment]
@RainbowMango Thanks, It's good to me.

**Comment by RainbowMango** [comment]
Good, I think you can approve it now.

**Comment by chaunceyjiang** [comment]
I also tested it on my local env. It can be imported as well.

/lgtm

**Comment by RainbowMango** [comment]
Thank you, I just tagged [v1.6.0](https://github.com/karmada-io/api/releases/tag/v1.6.0).

**Pull request merged**
