### PR TITLE
Sync APIs from karmada repo based on v1.1.0

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
Sync APIs from karmada repo based on v1.1.0.

**Which issue(s) this PR fixes**:
Fixes #https://github.com/karmada-io/karmada/issues/1669
Fixes #9 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Synced API based on Karmada v1.1.0.
```

cc @stingshen

### CODE REVIEW

**Comment by RainbowMango** [comment]
@riverzhang Can we move on forward with this patch?

In the future, we can use [kubernetes/publishing-bot](https://github.com/kubernetes/publishing-bot) to do the sync work. Both for API and clients.

**Comment by stingshen** [comment]
> @riverzhang Can we move on forward with this patch?
> 
> In the future, we can use [kubernetes/publishing-bot](https://github.com/kubernetes/publishing-bot) to do the sync work. Both for API and clients.

It seems that @riverzhang reacted with a thumps up...

**Comment by RainbowMango** [comment]
Ok. Let's do it.

**Comment by RainbowMango** [comment]
@stingshen Just cut a new release [v1.1.0](https://github.com/karmada-io/api/releases/tag/v1.1.0).

**Comment by stingshen** [comment]
> @stingshen Just cut a new release [v1.1.0](https://github.com/karmada-io/api/releases/tag/v1.1.0).

Thank you!

**Pull request merged**
