### PR TITLE
Sync APIs from karmada repo based on v1.7.0

### PR DESCRIPTION
**Pull request by RainbowMango**
This PR syncs APIs from karmada-io/karmada release v1.7.0.
Fixes https://github.com/karmada-io/karmada/issues/4314

### CODE REVIEW

**Review by chaunceyjiang — COMMENTED** [review]
Thanks~
/lgtm

**Review by liangyuanpeng — APPROVED** [review]

**Comment by RainbowMango** [comment]
:) 
@liangyuanpeng Are you relying on this?

**Comment by liangyuanpeng** [comment]
> Are you relying on this?

Actually no, i'm using `karnada-io/karmada@v1.7.0/pkg/apis`, But this PR is fine for me :)

**Comment by calvin0327** [comment]
@RainbowMango Thanks, It's good to me

**Pull request merged**
